// Generated by https://quicktype.io



export class Producto {

    constructor(
        public nombre: string,
        public pVenta: number,
        public pCompra?: number,
        public descripcion?: string,
        public _id?: string,
        public codBarra?: string,
        public stock?: number,
    ) {}
}
